import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { createRequire } from "node:module";
import ts from "typescript";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

const nativeRequire = createRequire(__filename);
const root = path.resolve(__dirname, "../../..");
const cache = new Map<string, { exports: Record<string, unknown> }>();

// Load the actual first-party TSX component without starting Next or Auth.
// External dependencies are real installed packages; no product module is mocked.
function load(file: string): Record<string, unknown> {
  const cached = cache.get(file);
  if (cached) return cached.exports;
  const relative = path.relative(root, file).replaceAll("\\", "/");
  if (!/^(components|lib)\//.test(relative)) throw new Error(`Unapproved first-party module: ${relative}`);
  const source = fs.readFileSync(file, "utf8");
  const result = ts.transpileModule(source, { compilerOptions: {
    module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX, target: ts.ScriptTarget.ES2022,
    esModuleInterop: true,
  } });
  const compiledModule = { exports: {} }; cache.set(file, compiledModule);
  function resolve(name: string) {
    if (!name.startsWith(".") && !name.startsWith("@/")) return nativeRequire(name);
    const base = name.startsWith("@/") ? path.join(root, name.slice(2)) : path.resolve(path.dirname(file), name);
    const target = [base + ".ts", base + ".tsx", path.join(base, "index.ts"), path.join(base, "index.tsx")].find((p) => fs.existsSync(p));
    if (!target) throw new Error(`Unresolved first-party dependency: ${name}`);
    return load(target);
  }
  const wrapper = new vm.Script(`(function(require,module,exports){${result.outputText}\n})`, { filename: file }).runInThisContext();
  wrapper(resolve, compiledModule, compiledModule.exports);
  return compiledModule.exports;
}

export function renderHomeEditor() {
  const { DashboardHomeWidgetCard } = load(path.join(root, "components/dashboard/dashboard-home/dashboard-home-widget-card.tsx")) as typeof import("../../../components/dashboard/dashboard-home/dashboard-home-widget-card");
  // Fixed test fixture, not generated by the production default-layout function.
  const fixtures = [
    { type: "greeting", width: 5, height: 1 },
    { type: "todos", width: 3, height: 3 },
    { type: "announcements", width: 2, height: 2 },
    { type: "clock", width: 2, height: 2 },
    { type: "invite", width: 3, height: 2 },
  ] as const;
  const copy = { adjustWidget: "调整组件", removeWidget: "移除组件", sizeLabel: (w: number, h: number) => `${w} × ${h}`,
    widgets: Object.fromEntries(fixtures.map(({ type }) => [type, { title: type, description: type }])) } as import("../../../components/dashboard/dashboard-home/dashboard-home-customizer-copy").HomeCustomizerCopy;
  const noop = () => {};
  // React supplies the required child via createElement's third argument.
  // This type-only facade accommodates factory typing; it is the same real component.
  // Avoid JSX here because Playwright converts test JSX to its component-test metadata.
  type Props = React.ComponentProps<typeof DashboardHomeWidgetCard>;
  const CardWithChildArgument = DashboardHomeWidgetCard as React.ComponentType<Omit<Props, "children"> & { children?: React.ReactNode }>;
  return renderToStaticMarkup(React.createElement("main", null, fixtures.map((fixture, index) => React.createElement(CardWithChildArgument, {
    key: fixture.type, widget: { ...fixture, id: `fixture-${fixture.type}`, x: 0, y: index }, copy,
    deleting: false, dragging: false, editing: true, entering: false, index,
    onAdjust: noop, onDragEnd: noop, onDragStart: noop, onMove: noop, onRemove: noop, onResize: noop,
    onResizeEnd: noop, onResizeStart: noop, pauseWiggle: true, resizing: false,
  }, React.createElement("p", null, `Synthetic ${fixture.type} body`)))));
}
